<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Inedo.Extensions.Gitea</RootNamespace>
    <AssemblyName>Gitea</AssemblyName>
    <LangVersion>latest</LangVersion>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Inedo.SDK" Version="4.0.0-ci.7" ExcludeAssets="runtime" />
  </ItemGroup>
</Project>
